version: "3"
services:

  maven1:
    build: ./App1
    ports:
      - "7766:7777"
    container_name: app1
  
  maven2:
    build: ./App2
    ports:
       - "8866:8888"
    container_name: app2

  nginx:
    build: ./reverse-proxy
    ports:
      - "80:80"
    container_name: reverse-proxy
